
import { GoogleGenAI, Type } from "@google/genai";
import { stripBase64Prefix } from "./utils";

// =================================================================================
// TODO: 请在此处填入您提供的 API Base URL
// 1. 如果使用官方 Key，此地址会被自动忽略。
// 2. 如果使用渠道 Key，请确保此地址是兼容 Gemini 格式的 (例如 /v1beta/models...)
//    注意：OpenAI 格式的地址 (v1/chat/completions) 是不被 GoogleGenAI SDK 支持的。
const VENDOR_BASE_URL = 'https://generativelanguage.googleapis.com'; 
// =================================================================================

// Helper to get fresh instance with priority on LocalStorage Custom Key
export const getApiKey = () => {
  const customKey = localStorage.getItem('SCW_API_KEY');
  const envKey = process.env.API_KEY;
  // 核心逻辑：如果有 customKey（哪怕是乱填的），优先返回 customKey
  // 只有当 customKey 为 null/空字符串时，才回退到 envKey
  return customKey || envKey;
};

const getAI = () => {
  const apiKey = getApiKey();
  const customKey = localStorage.getItem('SCW_API_KEY');
  
  // --- DEBUG START: 打印密钥信息帮助排查问题 ---
  console.group('%c[Gemini Service Debug]', 'color: #C41E3A; font-weight: bold; padding: 4px; border: 1px solid #C41E3A; border-radius: 4px;');
  console.log(`Time       : ${new Date().toLocaleTimeString()}`);
  
  if (customKey) {
    console.log(`Key Source : 🔴 用户自定义 (localStorage)`);
    console.log(`Raw Value  : "${customKey}"`);
  } else {
    console.log(`Key Source : 🟢 系统默认 (process.env)`);
  }
  
  const maskedKey = apiKey ? `${apiKey.substring(0, 6)}...${apiKey.substring(apiKey.length - 4)}` : 'NULL';
  console.log(`Active Key : ${maskedKey}`);
  
  const options: any = { apiKey };
  
  // 智能分流逻辑
  if (apiKey && !apiKey.startsWith('AIza')) {
    console.log(`Routing    : 🔀 检测到非官方 Key，尝试使用渠道线路`);
    console.log(`Base URL   : ${VENDOR_BASE_URL}`);
    options.baseUrl = VENDOR_BASE_URL;
  } else {
    console.log(`Routing    : 🌐 检测到官方 Key (AIza开头) 或 默认设置，使用官方线路`);
  }
  console.groupEnd();
  // --- DEBUG END ---

  return new GoogleGenAI(options);
};

export const generateDoorVisualization = async (
  coupletBase64: string, 
  doorStyle: string,
  doorBase64?: string | null
): Promise<string> => {
  const ai = getAI();
  const coupletData = stripBase64Prefix(coupletBase64);
  
  let contents: any[] = [];

  if (doorBase64 && doorStyle === "自家大门") {
    const doorData = stripBase64Prefix(doorBase64);
    const prompt = `
      You are an expert product photographer and visual editor for an e-commerce store.
      Image 1 is a Chinese New Year couplet product (the merchandise).
      Image 2 is the target installation scene (a door).
      
      Task: Create a high-converting marketing image by realistically superimposing the couplet (Image 1) onto the door (Image 2).
      
      Requirements:
      1. **Sales Focus**: The couplet must look premium, high-quality, and clearly visible.
      2. Perspective & Lighting: Perfectly match the door's angle and environmental lighting.
      3. Placement: Adhere to traditional Chinese customs (vertical scrolls on sides, horizontal on top).
      4. Texture: Retain the texture of the couplet (e.g., velvet, gold stamping) to show quality.
    `;
    
    contents = [
      { inlineData: { mimeType: 'image/png', data: coupletData } },
      { inlineData: { mimeType: 'image/png', data: doorData } },
      { text: prompt }
    ];
  } else {
    const prompt = `
      You are an expert product photographer. 
      Task: Generate a high-quality lifestyle product shot of this Chinese New Year couplet pasted on a ${doorStyle}.
      
      Requirements:
      1. Atmosphere: Festive, warm, and inviting (Marketing style).
      2. Product Clarity: The couplet text and details must be sharp and readable to attract buyers.
      3. Composition: Professional framing suitable for social media ads.
      4. Realism: Natural shadows and material textures.
    `;
    
    contents = [
      { inlineData: { mimeType: 'image/png', data: coupletData } },
      { text: prompt }
    ];
  }

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts: contents }
  });

  const parts = response.candidates?.[0]?.content?.parts;
  if (parts) {
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
  }
  
  throw new Error("No image generated by the model.");
};

export const generateSocialCopy = async (
  titleTemplate: string,
  contentTemplate: string
): Promise<{ title: string; content: string }> => {
  const ai = getAI();

  const prompt = `
    You are a Senior Content Operations Specialist (资深电商运营) for a Chinese New Year Couplet store.
    Your goal is to write high-converting social media copy (Xiaohongshu style) to SELL this product.

    Product Name/Title: "${titleTemplate}"
    Key Selling Points/Description: "${contentTemplate}"

    Requirements:
    1. **Target Audience**: Homeowners, young people looking for "ritual sense" (仪式感), or gift buyers.
    2. **Tone**: Enthusiastic, trustworthy, creating a sense of urgency (e.g., "High stock moving fast", "Premium quality").
    3. **Structure**:
       - **Headline**: Must be click-bait worthy (e.g., "My neighbors are asking where I bought this!", "Most beautiful couplet of 2024").
       - **Body**: Highlight material quality (flocking, gold stamping), the meaning of the text, and the visual upgrade to the home.
       - **Call to Action**: Soft sell (e.g., "Link in bio", "Comment for link").
    4. **Format**: Use relevant emojis (🧧, ✨, 🏠) and bullet points for readability.
    5. Output strictly valid JSON.
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          content: { type: Type.STRING }
        },
        required: ["title", "content"]
      }
    }
  });

  const jsonStr = response.text;
  if (!jsonStr) throw new Error("No text generated");
  
  try {
    return JSON.parse(jsonStr);
  } catch (e) {
    throw new Error("Failed to parse JSON response");
  }
};

export const extractInfoFromUrlContent = async (
  scrapedText: string
): Promise<{ title: string; content: string }> => {
  const ai = getAI();
  const context = scrapedText.slice(0, 30000); 

  const prompt = `
    你是一个电商数据分析师。请分析以下网页内容，提取商品的核心营销信息。
    
    网页原始内容：
    """
    ${context}
    """
    
    任务要求：
    1. 提取商品【标准名称】作为标题。
    2. 提取【核心卖点】（如材质、工艺、尺寸、寓意）作为内容，整理成简洁的营销短语。
    3. 过滤掉无用的导航、促销倒计时等干扰信息。
    4. 返回 JSON 格式。
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          content: { type: Type.STRING }
        },
        required: ["title", "content"]
      }
    }
  });

  const jsonStr = response.text;
  if (!jsonStr) throw new Error("No text generated");
  try { return JSON.parse(jsonStr); } catch (e) { return { title: "", content: "" }; }
};

export const extractInfoFromUrlViaSearch = async (
  url: string
): Promise<{ title: string; content: string }> => {
  const ai = getAI();

  const prompt = `
    Analyze this e-commerce URL: ${url}
    
    Task:
    1. Identify the Product Title.
    2. Summarize the Key Selling Points (features, benefits) in Chinese.
    
    Format as JSON: { "title": "...", "content": "..." }
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: { tools: [{ googleSearch: {} }] }
    });

    let text = response.text || "";
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    
    if (jsonMatch) {
      try { return JSON.parse(jsonMatch[0]); } catch (e) {}
    }
    if (text.length > 10) {
        return { title: "自动提取商品名", content: text.substring(0, 300) };
    }
  } catch (error) {}

  return { title: "AI 智能提取结果", content: "请手动补充卖点。" };
};

export const generateCoupletVideo = async (image: string): Promise<string> => {
  const ai = getAI();
  const imageData = stripBase64Prefix(image);
  
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt: 'Professional product video, slow zoom in, high quality, 4k, showcasing the texture of the Chinese New Year couplet on the door.',
    image: {
      imageBytes: imageData,
      mimeType: 'image/png', 
    },
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: '9:16'
    }
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 5000));
    operation = await ai.operations.getVideosOperation({operation: operation});
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  if (!downloadLink) throw new Error("Failed to generate video URI.");

  return downloadLink;
};
